# Using Current Data To Make Recommendations
### Model #1: (Classification - Fully Paid vs. Default) 
### Model #2: ( Regression - Annualized Return %)

In [1]:
import pandas as pd
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
from functions_and_objects import (impute_means_zeros_maxs_X,parse_percentage,
                                   clean_new_LC_data_classification_current,preprocessing_current, 
                                   columns_list, nan_max_cols, nan_mean_cols, nan_zero_cols, dtype,
                                   one_hot_encode_current, concat_X_and_6ohe_dfs,
                                   prep_all_df_for_classification)
from functions_and_objects import (prep_df_for_regression_current,
                                   calc_annu_return,impute_annu_return_to_y,
                                   scale_current)

import joblib
from sklearn.metrics import (accuracy_score, precision_score, recall_score, #classification
                             f1_score, roc_auc_score, roc_curve,precision_recall_fscore_support, #classification
                             r2_score,mean_squared_error) #regression

%load_ext autoreload
%autoreload 2

### Import New Data from 2018-2019

- These files contain complete loan data for all loans issued through the time period stated, including the current loan status (Current, Late, Fully Paid, etc.) and latest payment information. The file containing loan data through the "present" contains complete loan data for all loans issued through the previous completed calendar quarter.

In [2]:
raw_q12019 = pd.read_csv('~/peervest/lc_data/LoanStats_securev1_2019Q1.csv',header=1)
raw_q42018 = pd.read_csv('~/peervest/lc_data/LoanStats_securev1_2018Q4.csv',header=1)
raw_q32018 = pd.read_csv('~/peervest/lc_data/LoanStats_securev1_2018Q3.csv',header=1)
raw_q22018 = pd.read_csv('~/peervest/lc_data/LoanStats_securev1_2018Q2.csv',header=1)
raw_q12018 = pd.read_csv('~/peervest/lc_data/LoanStats_securev1_2018Q1.csv',header=1)
dfs_list = [raw_q42018,
            raw_q32018,
            raw_q22018,
            raw_q12018]

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,144,145,146) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,129,130,131,134,135,136,139,144,145,146) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


### Clean Data

In [3]:
#use cleaning function "current" because 
#we're making predictions on current loans
#rather than using labelled/completed data

clean_lc_df_current = clean_new_LC_data_classification_current(dfs_list) #takes in dfs_list, outputs clean_lc_df

/home/jupyter/peervest/functions_and_objects.py:217: FutureWarning: Passing datetime64-dtype data to TimedeltaIndex is deprecated, will raise a TypeError in a future version
  raw_lc_df['earliest_cr_line'] = pd.to_timedelta(pd.to_datetime(raw_lc_df['earliest_cr_line'])).dt.days


### Preprocess, no train-test-split: entire dataset is our test data

In [4]:
# takes in clean_lc_df_current, outputs X_current, y_current
X_current, y_current = preprocessing_current(clean_lc_df_current)

In [5]:
print(X_current.shape)
print(y_current.shape)

(361423, 101)
(361423, 1)


### One Hot Encode for both Models

In [6]:
(ohe_home_ownership, ohe_purpose, ohe_zip_code, 
 ohe_application_type, ohe_sub_grade, ohe_emp_title_2) = one_hot_encode_current(X_current)

In [7]:
X_current_classif = concat_X_and_6ohe_dfs(X_current, ohe_home_ownership, ohe_purpose, ohe_zip_code,
                                          ohe_application_type, ohe_sub_grade, ohe_emp_title_2)
X_current_regr = concat_X_and_6ohe_dfs(X_current, ohe_home_ownership, ohe_purpose, ohe_zip_code, 
                                       ohe_application_type, ohe_sub_grade, ohe_emp_title_2)

In [8]:
print(X_current_classif.shape)
print(X_current_regr.shape)

(361423, 1133)
(361423, 1133)


### Prep X_current for Classification

- reset index

In [9]:
X_current_classif.set_index('index',inplace=True)

- drop non-numeric & OHE source columns

In [10]:
prep_all_df_for_classification(X_current_classif) #drops columns inplace

In [11]:
X_current_classif.shape

(361423, 1124)

### X_current is ready to input into Classification Model

In [22]:
print(y_current.shape)
y_current.head()

(361423, 1)


class_pred
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

###### Load Model JobLib

In [15]:
loaded_log_reg_v1 = joblib.load('log_reg_v1.joblib')

In [17]:
current_class_preds = loaded_log_reg_v1.predict(X_current_classif)
current_class_preds_proba = loaded_log_reg_v1.predict_proba(X_current_classif)

In [18]:
len(current_class_preds_proba)

361423

In [28]:
loaded_log_reg_v1.classes_

array([0, 1])

In [50]:
current_class_preds_proba[:,0]

array([1., 1., 1., ..., 1., 1., 1.])

In [57]:
y_current['prob_default'] = current_class_preds_proba[:,0]

### Prep X_current for Regression

- reset index

In [52]:
X_current_regr.set_index('index',inplace=True)

- calculate annual return & create new target dataframe

In [53]:
# returns the annualized return column as a DF (y_future_regr) & both target columns as a dataframe (y_future)
y_current_regr, y_current = impute_annu_return_to_y(X_current_regr,y_current)

- drop non-numeric & OHE source columns

In [54]:
prep_df_for_regression_current(X_current_regr)

In [55]:
X_current_regr_scaled = scale_current(X_current_regr)

In [68]:
X_current_regr_scaled.shape

(361423, 1124)

###### Load Ridge Regression Model JobLib

In [65]:
loaded_ridge_reg_v1 = joblib.load('ridge_lin_reg_v1.joblib')

In [66]:
current_return_preds = loaded_ridge_reg_v1.predict(X_current_regr_scaled)

- Positive annu_return values where loan_status==0 likely indicates a successful debt collection process

In [71]:
y_current

annu_return  prob_default
0         -0.963885      1.000000
1         -0.972364      1.000000
2         -0.859431      1.000000
3         -0.980185      1.000000
4         -0.982816      1.000000
5         -0.963888      1.000000
6         -0.988391      1.000000
7         -0.983512      1.000000
8         -0.984809      1.000000
9         -0.978654      1.000000
10        -0.963887      1.000000
11        -0.963888      1.000000
12        -0.966224      1.000000
13        -0.991567      1.000000
14        -0.986618      1.000000
15        -0.971224      1.000000
16        -0.971660      1.000000
17        -0.977839      1.000000
18        -0.983509      1.000000
19        -0.974773      1.000000
20        -0.992524      1.000000
21        -0.996513      1.000000
22        -0.963886      1.000000
23        -0.972814      1.000000
24        -0.357041      1.000000
25        -0.973700      1.000000
26        -0.986935      1.000000
27        -0.974490      1.000000
28        -0.982836      1.000000
29        -0.983513      1.000000
...             ...           ...
361393    -0.290279      1.000000
361394    -0.387514      1.000000
361395    -0.322001      1.000000
361396    -0.341844      1.000000
361397    -0.322004      1.000000
361398    -0.391450      1.000000
361399    -0.357682      1.000000
361400    -0.385425      1.000000
361401    -0.334359      1.000000
361402    -0.351381      1.000000
361403    -0.299381      1.000000
361404    -0.341844      1.000000
361405    -0.391450      1.000000
361406    -0.397403      1.000000
361407    -0.535590      1.000000
361408    -0.365895      1.000000
361409    -0.321949      1.000000
361410    -0.349179      1.000000
361411    -0.395750      1.000000
361412    -0.399467      1.000000
361413    -0.368675      1.000000
361414    -0.395422      0.999999
361415    -0.361756      1.000000
361416    -0.502557      1.000000
361417    -0.290563      1.000000
361418    -0.465482      1.000000
361419    -0.357674      1.000000
361420    -0.348179      1.000000
361421    -0.368722      1.000000
361422    -0.360001      1.000000

[361423 rows x 2 columns]

In [72]:
current_return_preds

array([[ 0.01616499],
       [-0.02710525],
       [ 0.25884256],
       ...,
       [ 0.09232062],
       [ 0.2400825 ],
       [ 0.29361946]])

In [73]:
y_predictions = y_current
y_predictions['return_preds'] = current_return_preds

In [74]:
y_predictions.drop(columns=['annu_return'])

annu_return  prob_default  return_preds
0         -0.963885      1.000000      0.016165
1         -0.972364      1.000000     -0.027105
2         -0.859431      1.000000      0.258843
3         -0.980185      1.000000     -0.094744
4         -0.982816      1.000000     -0.454300
5         -0.963888      1.000000     -0.054143
6         -0.988391      1.000000     -0.583992
7         -0.983512      1.000000     -0.130022
8         -0.984809      1.000000     -0.273052
9         -0.978654      1.000000     -0.264439
10        -0.963887      1.000000     -0.163939
11        -0.963888      1.000000     -0.084360
12        -0.966224      1.000000      0.013257
13        -0.991567      1.000000     -0.221730
14        -0.986618      1.000000     -0.713796
15        -0.971224      1.000000     -0.285888
16        -0.971660      1.000000     -0.215681
17        -0.977839      1.000000     -0.434286
18        -0.983509      1.000000     -0.494526
19        -0.974773      1.000000     -0.077466
20        -0.992524      1.000000     -0.482456
21        -0.996513      1.000000     -0.569618
22        -0.963886      1.000000      0.075864
23        -0.972814      1.000000     -0.106664
24        -0.357041      1.000000      0.493500
25        -0.973700      1.000000     -0.060826
26        -0.986935      1.000000     -0.255905
27        -0.974490      1.000000     -0.019344
28        -0.982836      1.000000     -0.684938
29        -0.983513      1.000000     -0.736131
...             ...           ...           ...
361393    -0.290279      1.000000      0.701194
361394    -0.387514      1.000000      0.302638
361395    -0.322001      1.000000      0.468283
361396    -0.341844      1.000000      0.306765
361397    -0.322004      1.000000      0.439941
361398    -0.391450      1.000000      0.603395
361399    -0.357682      1.000000      0.620444
361400    -0.385425      1.000000      0.566018
361401    -0.334359      1.000000      0.228507
361402    -0.351381      1.000000      0.773770
361403    -0.299381      1.000000      0.549686
361404    -0.341844      1.000000      0.393378
361405    -0.391450      1.000000      0.545853
361406    -0.397403      1.000000      0.793181
361407    -0.535590      1.000000     -0.005009
361408    -0.365895      1.000000      0.824037
361409    -0.321949      1.000000     -0.008295
361410    -0.349179      1.000000      0.763782
361411    -0.395750      1.000000      0.214599
361412    -0.399467      1.000000      0.562737
361413    -0.368675      1.000000     -0.054598
361414    -0.395422      0.999999      0.122406
361415    -0.361756      1.000000      0.263315
361416    -0.502557      1.000000     -0.002814
361417    -0.290563      1.000000      0.433557
361418    -0.465482      1.000000      0.020636
361419    -0.357674      1.000000      0.129858
361420    -0.348179      1.000000      0.092321
361421    -0.368722      1.000000      0.240082
361422    -0.360001      1.000000      0.293619

[361423 rows x 3 columns]